<?php

namespace RtxLabs\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserAttributeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAttributeRepository extends EntityRepository
{
}